spring:
  application:
    name: eureka-service
  thymeleaf:
    cache: false
    
server:
  port: 8761
  session:
    cookie:
      name: UISESSION
      

     
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: https://notewitch-eureka.herokuapp.com/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 0 


zuul:
  prefix: /api
  routes:
    db-service:
      path: /db-service/**
      url: https://notewitch-dbservice.herokuapp.com/
    location-service:
      path: /location-service/**
      url: http://localhost:8302
      
security:
  basic:
    enabled: false  
  oauth2:
    client:
      client-id: clientId
      client-secret: secret
      access-token-uri: https://notewitch-auth-server.herokuapp.com/auth/oauth/token
      user-authorization-uri: https://notewitch-auth-server.herokuapp.com/auth/oauth/authorize
    resource:
      user-info-uri: https://notewitch-auth-server.herokuapp.com/getCurrentUser
      preferTokenInfo: false  
  sessions: ALWAYS 
  
proxy:
  auth:
    routes:
      db-service: oauth2
      location-service: oauth2
      